volumes:
  postgres_data:
    driver: "local"
  maven_cache:

networks:
  wise_network:
    driver: "bridge"

services:
  postgres:
    image: postgres:alpine
    container_name: postgres_product_compose
    restart: always
    environment:
      - POSTGRES_DB=wiseCommerceProduct
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - TZ=America/Sao_Paulo
    ports:
      - "5445:5432"
    networks:
      - wise_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: wise_commerce_product_compose
    volumes:
      - maven_cache:/root/.m2
    depends_on:
      - postgres
    ports:
      - "8089:8080"
    networks:
      - wise_network